--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DustinMcNeese/PMMP-AntiCheat
build-by-default: true
branches:
- main
projects:
  AntiCheat: 
    Path: "" 
    Icon: meta/636163145966192964.png
...
