---
###########################################################################
#  METADATA OF CONFIG                                                     #
#  DO NOT CHANGE UNLESS YOU KNOW WHAT                                     #
#  YOU ARE DOING!!!                                                       #
   Plugin-Version: 3.0.0                                           #
   Config-Version: 5                                           #
###########################################################################
# REMEMBER: This AntiCheat software was made to prevent cheats            #
# which are not detected by pocketmine itself. While AC can              #
#r un as a standalone plugin I still highly                               #
# reccomend to turn Pocketmine's Native AntiCheat on if it                #
# doesn't cause issues for you.                                           #
###########################################################################
#enable/disable by defualt they are all enabled
noclip: enabled
freeze: enabled
xray: enabled 
fly: enabled 
killaura: enabled 
speed: enabled 
allopwarn: enabled 
---
